# Generated by Django 5.1.5 on 2025-01-26 21:18

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=apps.users.models.CustomPasswordField(max_length=128, verbose_name='password'),
        ),
    ]
