# Generated by Django 5.1.5 on 2025-01-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ['joined_at'], 'verbose_name': 'Group Member', 'verbose_name_plural': 'Group Members'},
        ),
        migrations.AlterModelTable(
            name='group',
            table='Groups',
        ),
        migrations.AlterModelTable(
            name='groupmember',
            table='GroupMembers',
        ),
    ]
