# Generated by Django 5.1.5 on 2025-01-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_options_alter_groupmember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at'], 'verbose_name': 'Group', 'verbose_name_plural': 'All Groups'},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ['joined_at'], 'verbose_name': 'Group Member', 'verbose_name_plural': 'All Group Members'},
        ),
    ]
